services:
  backend:
    build: .
    container_name: inex-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: bitnami/postgresql:16
    container_name: inex-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE}
    volumes:
      - pgdata:/bitnami/postgresql
    restart: unless-stopped

volumes:
  pgdata:
